name: npm
description: null
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.22.2'

dependencies:
  collection: ^1.18.0
  device_preview: ^1.3.1
  dio: ^5.9.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3+1
  freezed_annotation: ^3.1.0
  gap: ^3.0.1
  go_router: ^17.0.1
  hooks_riverpod: ^3.1.0
  json_annotation: ^4.9.0
  markdown_widget: ^2.3.2+3
  riverpod_annotation: ^4.0.0
  shared_preferences: ^2.5.4
  slang: ^4.12.1
  slang_flutter: ^4.12.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: 1.26.3
  golden_toolkit: ^0.15.0
  flutter_lints: ^6.0.0
  riverpod_generator: ^4.0.0+1
  build_runner: ^2.11.0
  build_verify: ^3.1.1
  custom_lint: ^0.8.1
  riverpod_lint: ^3.1.0
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  go_router_builder: ^4.2.0
  slang_build_runner: ^4.12.1

flutter:
  uses-material-design: true
  assets:
    - assets/app/