name: npm
description: null
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.22.2'

dependencies:
  collection: ^1.18.0
  device_preview: ^1.3.1
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  freezed_annotation: ^3.1.0
  gap: ^3.0.1
  go_router: ^16.1.0
  hooks_riverpod: ^2.6.1
  json_annotation: ^4.9.0
  markdown_widget: ^2.3.2+3
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.5.3
  slang: ^4.7.3
  slang_flutter: ^4.8.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: 1.26.2
  golden_toolkit: ^0.15.0
  flutter_lints: ^6.0.0
  riverpod_generator: ^2.6.5
  build_runner: ^2.4.15
  build_verify: ^3.1.1
  custom_lint: ^0.7.6
  riverpod_lint: ^2.6.5
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  go_router_builder: ^3.0.1
  slang_build_runner: ^4.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/app/