name: npm
description: null
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.16.8'

dependencies:
  collection: ^1.18.0
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  go_router: ^14.0.2
  hooks_riverpod: ^2.5.1
  json_annotation: ^4.9.0
  markdown_widget: ^2.3.2+3
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.2.3
  slang: ^3.30.2
  slang_flutter: ^3.30.0
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  test:
  flutter_lints: ^3.0.2
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.9
  build_verify: ^3.1.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  go_router_builder: ^2.6.1
  slang_build_runner: ^3.30.0

flutter:
  uses-material-design: true
  assets:
    - assets/app/