name: npm
description: null
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.22.2'

dependencies:
  collection: ^1.18.0
  device_preview: ^1.2.0
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  go_router: ^14.3.0
  hooks_riverpod: ^2.6.1
  json_annotation: ^4.9.0
  markdown_widget: ^2.3.2+3
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.3.2
  slang: ^4.1.0
  slang_flutter: ^4.1.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: 1.25.7
  golden_toolkit: ^0.15.0
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.13
  build_verify: ^3.1.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  go_router_builder: ^2.7.1
  slang_build_runner: ^4.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/app/