name: npm
description: null
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  collection: ^1.18.0
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  go_router: ^12.1.3
  hooks_riverpod: ^2.4.0
  json_annotation: ^4.8.1
  markdown_widget: ^2.3.2+2
  riverpod_annotation: ^2.3.1
  slang: ^3.28.0
  slang_flutter: ^3.27.0
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7
  build_verify: ^3.1.0
  custom_lint: ^0.5.7
  riverpod_lint: ^2.3.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  go_router_builder: ^2.4.0
  test: ^1.24.9
  slang_build_runner: ^3.27.0

flutter:
  uses-material-design: true
  assets:
    - assets/app/